<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Deskripsi_bi bi-plus display-6</name>
   <tag></tag>
   <elementGuidId>4d66baff-da9e-4488-b6f6-25475b56fe0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-images']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-plus.display-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cbdf71e2-d044-4695-9a37-18dfe2b8d231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-plus display-6</value>
      <webElementGuid>3d21b260-d85c-4fe5-a199-cc154893d26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-images&quot;)/div[@class=&quot;form-image rounded-4 img-preview&quot;]/i[@class=&quot;bi bi-plus display-6&quot;]</value>
      <webElementGuid>b3d9d363-36e9-4b7e-bc76-2306ab01f360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/div/i</value>
      <webElementGuid>0e1fc1fb-24b1-43c4-9496-e80a179891bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/i</value>
      <webElementGuid>13f61611-035c-400d-bd4b-7dcfba88b508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
